### ISSUE TITLE
Verify Doxygen works

### ISSUE THREAD

**Issue by rdong8** [rdong8/cpp_project#2]
My distro (Fedora 39) currently has only Doxygen 1.9.7. The code in this repo uses C++20 modules that are not supported until 1.9.8, so I haven't been able to test whether the documentation is being generated properly yet.

**Comment by albert-github** [comment]
Based on https://github.com/doxygen/doxygen/discussions/11088 it looks doxygen 1.12.0 does work (but doxygen 1.9.8 does not give results).

**Comment by rdong8** [comment]
Thank you so much for your help, I wouldn't have caught that.
